# This is an appspec.yml template file for use with an EC2/On-Premises deployment in AWS CodeDeploy.
# The lines in this template starting with the hashtag symbol are
#   instructional comments and can be safely left in the file or
#   ignored.
# For help completing this file, see the "AppSpec File Reference" in the
#   "AWS CodeDeploy User Guide" at
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/share/applications/poll
permissions:
  - object: /usr/local/share/applications
    pattern: "poll"
    owner: ec2-user
    group: ec2-user
  - object: /usr/local/share/applications/poll
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/clean_instance.sh
      timeout: 6000
      runas: root
  AfterInstall:
#    - location: scripts/install_os_dependencies.sh
#      timeout: 6000
#      runas: root
#    - location: scripts/install_python_dependencies.sh
#      timeout: 6000
#      runas: ec2-user
    - location: scripts/migrate.sh
      timeout: 6000
      runas: ec2-user
#    - location: scripts/ngnix.sh
#      timeout: 6000
#      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 6000
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 6000
      runas: ec2-user